/*CREATE DATABASE IF NOT EXISTS laboratorioPython;*/

CREATE TABLE IF NOT EXISTS codigo_area (
  codigo_area_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(15) NOT NULL UNIQUE,
  localidad VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS numeros (
  numero_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(15) NOT NULL UNIQUE,
  codigo_area_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (codigo_area_id) REFERENCES codigo_area(codigo_area_id)
);